apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::035823817457:role/JupyterES-ondemand-nodes-NodeInstanceRole-1G2H7Y0TWGL60
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::035823817457:user/townsenddw
      username: townsenddw
      groups:
        - system:masters
    - userarn: arn:aws:iam::035823817457:user/zsailer
      username: zsailer
      groups:
        - system:masters
    - userarn: arn:aws:iam::035823817457:user/ellisonbg
      username: ellisonbg
      groups:
        - system:masters