---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Deployment for Jupyter ES'


Resources:
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref VPC

  EKSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: eksServiceRole
      AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "eks.amazonaws.com"
              Action:
                - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: CalpolyDataScience
      ResourcesVpcConfig: 
        SecurityGroupIds: 
          - !Ref ControlPlaneSecurityGroup 
        SubnetIds: [ !Ref Subnet01, !Ref Subnet02, !Ref Subnet03 ]
      RoleArn: !GetAtt EKSRole.Arn

